# Generated by Django 5.1.6 on 2025-03-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
    ]
